version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    env_file:
      - ./.env
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      JWT_SECRET:  ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      MECHANIC_UNIVERSAL_PASSWORD: ${MECHANIC_UNIVERSAL_PASSWORD}
      PORT:        ${BACKEND_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: .
    env_file:
      - ./.env
    environment:
      REACT_APP_API_URL: "http://localhost:${BACKEND_PORT:-5000}"
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
